app/user/__init__.py
__author__ = 'GLFSI'

app/user/views.py
from flask import Blueprint, render_template, request, redirect, url_for,\
                  flash, send_file, session, escape, jsonify, g
from flask.ext import breadcrumbs
from flask_security import login_required, roles_accepted, current_user, utils
from datetime import datetime
from io import BytesIO
from sqlalchemy import desc
from app import app, db, stripe
from app.decorators import crossdomain
from app.models import Company, ReportGroup, ReportFolder, Document, Sponsor,\
                       Program, Role, User, ValidProgram, ReportSubscription,\
                       DocumentPurchase
from app.util.email import send_email


mod_user = Blueprint('user', __name__, url_prefix='/user')


@mod_user.route('/')
@mod_user.route('/dashboard')
@breadcrumbs.register_breadcrumb(mod_user, '.', '<i class="fa fa-fw fa-th-large"></i>')
@login_required
def dashboard():
    documents = current_user.get_recent_user_documents()
    public_documents = current_user.get_recent_public_documents()
    document_library = []
    for purchase in current_user.purchases:
        if len(document_library) <= 5:
            document_library.append(purchase.document)

    data = {
        'documents': documents,
        'public_documents': public_documents,
        'document_library': document_library,
        'subscriptions': current_user.subscriptions
    }

    return render_template('user/dashboard.html', data=data, dashboard=True)


@mod_user.route('/reports')
@breadcrumbs.register_breadcrumb(mod_user, '.reports', 'Reports')
@login_required
def documents_list():
    documents = current_user.get_user_documents()

    data = {
        'documents': documents
    }

    return render_template('user/documents.html', data=data)


@mod_user.route('/publicreports')
@breadcrumbs.register_breadcrumb(mod_user, '.publicreports', 'Public Reports')
@login_required
def public_documents_list():
    public_documents = current_user.get_public_documents()

    data = {
        'public_documents': public_documents
    }

    return render_template('user/publicdocuments.html', data=data)


@mod_user.route('/library')
@breadcrumbs.register_breadcrumb(mod_user, '.library', 'My Library')
@login_required
def library_list():
    document_library = []
    for purchase in current_user.purchases:
        document_library.append(purchase.document)

    data = {
        'document_library': document_library
    }

    return render_template('user/library.html', data=data)


def document_info_user_dlc(*args, **kwargs):
    document_id = request.view_args['document_id']
    document = Document.query.get(document_id)
    return [{'text': document.document_display_name, 'url': url_for('user.document_info', document_id=document_id)}]


@mod_user.route('/reports/info/<int:document_id>', methods=['GET'])
@breadcrumbs.register_breadcrumb(mod_user, '.reports.info', '',
                                 dynamic_list_constructor=document_info_user_dlc)
@login_required
def document_info(document_id):
    document = Document.query.get_or_404(document_id)
    if not document.is_free_access() and not document.get_purchase() and not document.is_subscribed():
        if not document.is_valid():
            flash('You do not have permission to view this resource.', 'error')
            return redirect(url_for('user.dashboard'))

    data = {
        'document': document
    }

    return render_template('user/documentinfo.html', data=data)


@mod_user.route('/cart')
@breadcrumbs.register_breadcrumb(mod_user, '.cart', 'Shopping Cart')
@login_required
def shopping_cart():
    cart = []
    total = 0
    try:
        for item in session['cart']:
            document = Document.query.filter_by(stripe_sku_id=item).first()
            if document:
                cart.append(document)
                total += document.price
    except KeyError:
        cart = []

    data = {
        'cart': cart,
        'total': total,
        'stripepk': app.config['STRIPE_KEYS']['PK']
    }

    return render_template('user/cart.html', data=data, simpletable=True)


# Subscription management

@mod_user.route('/subscriptions')
@breadcrumbs.register_breadcrumb(mod_user, '.subscriptions', 'Subscriptions')
@login_required
@crossdomain(origin='*')
def subscriptions_list():
    groups = ReportGroup.query.all()
    for group in groups:
        group.price = group.get_price()

    data = {
        'groups': groups,
        'subscriptions': current_user.subscriptions,
        'stripepk': app.config['STRIPE_KEYS']['PK']
    }

    return render_template('user/subscriptions.html', data=data, simpletable=True)


@mod_user.route('/subscriptions/subscribe/<int:group_id>')
@login_required
def subscribe_to(group_id):
    report_group = ReportGroup.query.get_or_404(group_id)
    
    if report_group.price > 0 and not report_group.is_free_access():
        flash('You must pay to access this group.', 'error')
        return redirect(url_for('user.subscriptions_list'))

    subscription = ReportSubscription()
    subscription.user_id = current_user.id
    subscription.report_group_id = group_id
    subscription.enable_notifications()

    db.session.add(subscription)
    db.session.commit()
    flash('Subscribed to %s.' % (subscription.report_group.report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/unsubscribe/<int:group_id>')
@login_required
def unsubscribe_to(group_id):
    subscription = ReportSubscription.query.filter_by(user_id=current_user.id).\
                   filter(ReportSubscription.report_group_id == group_id).first_or_404()
    report_group_name = subscription.report_group.report_group_name

    subscription.disable_notifications()

    if subscription.report_group.price > 0 and subscription.stripe_id:
        flash('You cannot unsubscribe to paid groups. Please disable auto-renewal if you wish to cancel.', 'error')
        return redirect(url_for('user.subscriptions_list'))

    db.session.delete(subscription)
    db.session.commit()
    flash('Unsubscribed from %s.' % (report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/notify/<int:group_id>')
@login_required
def enable_notifications_from(group_id):
    report_group = ReportGroup.query.get_or_404(group_id)
    if not report_group.is_subscribed() and not report_group.is_free_access():
        flash('You cannot receive notifications from unsubscribed groups.', 'error')
    else:    
        report_group.enable_notifications()
        db.session.commit()

    flash('Email notifications enabled for %s.' % (report_group.report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/unnotify/<int:group_id>')
@login_required
def disable_notifications_from(group_id):
    report_group = ReportGroup.query.get_or_404(group_id)
    
    report_group.disable_notifications()

    db.session.commit()
    flash('Email notifications disabled for %s.' % (report_group.report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/renew/<int:group_id>')
@login_required
def enable_autorenew(group_id):
    report_subscription = ReportSubscription.query.filter_by(user_id=current_user.id).\
                          filter(ReportSubscription.report_group_id == group_id).first_or_404()
    report_group_name = report_subscription.report_group.report_group_name
    
    # Get the Stripe Customer and reactivate their current subscription
    customer = stripe.Customer.retrieve(current_user.stripe_id)
    subscription = customer.subscriptions.retrieve(report_subscription.stripe_id)
    subscription.plan = report_subscription.report_group_id
    subscription.save()

    report_subscription.stripe_autorenew = 1

    db.session.commit()
    flash('Auto-renewal enabled for %s.' % (report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/unrenew/<int:group_id>')
@login_required
def disable_autorenew(group_id):
    report_subscription = ReportSubscription.query.filter_by(user_id=current_user.id).\
                          filter(ReportSubscription.report_group_id == group_id).first_or_404()
    report_group_name = report_subscription.report_group.report_group_name
    
    # Get the Stripe Customer and delete their subscription at_period_end
    customer = stripe.Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(report_subscription.stripe_id).delete(at_period_end=True)

    report_subscription.stripe_autorenew = 0

    db.session.commit()
    flash('Auto-renewal disabled for %s.' % (report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


## Payments and Subscription Management (AJAX)

@mod_user.route('/_addtocart')
@login_required
def add_to_cart(document_id=None):
    if request.args.get('document_id'):
        document_id = request.args.get('document_id')
    if not document_id:
        return jsonify(result=0)
    document = Document.query.get_or_404(document_id)
    try:
        session['cart'].append(str(document.stripe_sku_id))
    except KeyError:
        session['cart'] = []
        session['cart'].append(str(document.stripe_sku_id))

    return jsonify(result=1, name=document.document_display_name)


@mod_user.route('/_removefromcart')
@login_required
def remove_from_cart(document_id=None):
    if request.args.get('document_id'):
        document_id = request.args.get('document_id')
    if not document_id:
        return jsonify(result=0)
    document = Document.query.get_or_404(document_id)
    try:
        session['cart'].remove(str(document.stripe_sku_id))
    except KeyError:
        return jsonify(result=0)
    return jsonify(result=1, name=document.document_display_name)


@mod_user.route('/_clearcart')
@login_required
def clear_cart():
    try:
        del session['cart']

app/templates/user/_base.html
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="{{config.COMPANY_NAME}}">

    <title>{% if self.title() %}{% block title %}{% endblock %}{% else %}User Panel{% endif %} - {{config.APP_NAME}}</title>

    {% assets "panel_css" %}
      <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
    {% endassets %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.png') }}">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" type="text/css">
  </head>

  <body>
    <div id="outdated"></div>
    {% include '_navbar.html' %}
    <div class="container-fluid">
      <div class="row">
        <div class="sidebar" id="adminSideBar">
          <div class="sidebar-shadow">
            <ul class="nav nav-sidebar">
              <li><h2 class="sidebar-header">Access</h2></li>
              <li {% if url_for('user.dashboard') in request.path %}class="active"{% endif %}><a href="{{url_for('user.dashboard')}}"><span class="fa fa-fw fa-th-large" aria-hidden="true"></span> Dashboard</a></li>
              <li {% if url_for('user.public_documents_list') in request.path %}class="active"{% endif %}><a href="{{url_for('user.public_documents_list')}}"><span class="fa fa-fw fa-book" aria-hidden="true"></span> Public Reports</a></li>
              <li {% if url_for('user.documents_list') in request.path %}class="active"{% endif %}><a href="{{url_for('user.documents_list')}}"><span class="fa fa-fw fa-file" aria-hidden="true"></span> Reports</a></li>
              <li {% if url_for('user.library_list') in request.path %}class="active"{% endif %}><a href="{{url_for('user.library_list')}}"><span class="fa fa-fw fa-bookmark" aria-hidden="true"></span> My Library{% if current_user.purchases|count > 0 %} <span class="badge badge-success pull-right">{{current_user.purchases|count}}</span>{% endif %}</a></li>
              <li {% if url_for('user.subscriptions_list') in request.path %}class="active"{% endif %}><a href="{{url_for('user.subscriptions_list')}}"><span class="fa fa-fw fa-check-square-o" aria-hidden="true"></span> Subscriptions</a></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li><h2 class="sidebar-header">Account</h2></li>
              <li><a href="{{url_for('account')}}"><span class="fa fa-fw fa-wrench" aria-hidden="true"></span> Manage Account</a></li>
            </ul>
          </div>
        </div>
        <div class="row no-gutter">
          <div class="nav-breadcrumb">
            <ol class="breadcrumb">
              {%- if request.path == url_for('user.dashboard') -%}
              <li>Hello, {{current_user.first_name}}!</li>
              {%- else -%}
              {%- for breadcrumb in breadcrumbs -%}
              {%- if not loop.first -%}
              <li><a href="{{ breadcrumb.url }}"{% if loop.last %} class="active"{% endif %}>{{ breadcrumb.text|safe }}</a></li>
              {%- endif -%}
              {%- endfor -%}
              {%- endif -%}
            </ol>
          </div>
        </div>
        <div class="main" id="main">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>

    {% include '_footer.html' %}

    {% assets "panel_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% block scripts %}
    {% endblock %}
    {% include '_datatables.html' %}
    {% include '_flash.html' %}
    {% include '_analytics.html' %}
  </body>
</html>

app/templates/user/cart.html
{% if not dashboard %}
{% extends "user/_base.html" %}
{% block title %}Shopping Cart{% endblock %}
{% endif %}
{% block content %}
<div class="page-header">
    <h2>Shopping Cart</h2>
</div>
<div class="page-content">
    {% if data.cart|count > 0 %}
    <div class="loader"><span class="fa fa-spinner fa-spin fa-5x"></span></div>
    <div class="table-responsive" id="reports-wrapper" style="opacity: 0">
        <table class="table table-striped table-responsive table-hover nowrap" id="reports-table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class="all sort-by">Name</th>
                    <th class="min-phone-l">Group</th>
                    <th class="min-phone-l">Program</th>
                    <th class="all text-right">Price</th>
                    <th class="all text-right no-sort"></th>
                </tr>
            </thead>
            <tbody>
            {% for document in data.cart %}
                <tr>
                    <td class="info-link" data-href="{{url_for('user.document_info', document_id=document.document_id)}}">
                        {% if 'audio' in document.document_type %}
                        <span class="fa fa-fw file-audio fa-file-audio-o" aria-hidden="true"></span>
                        {% elif 'image' in document.document_type %}
                        <span class="fa fa-fw file-image fa-file-image-o" aria-hidden="true"></span>
                        {% elif 'pdf' in document.document_type %}
                        <span class="fa fa-fw file-pdf fa-file-pdf-o" aria-hidden="true"></span>
                        {% elif 'text' in document.document_type %}
                        <span class="fa fa-fw file-text fa-file-text-o" aria-hidden="true"></span>
                        {% elif 'video' in document.document_type %}
                        <span class="fa fa-fw file-movie fa-file-movie-o" aria-hidden="true"></span>
                        {% else %}
                        <span class="fa fa-fw file-other fa-file-code-o" aria-hidden="true"></span>
                        {% endif %}
                        {{document.document_display_name}}
                    </td>
                    <td class='search-link' data-search='{{document.report_folder.report_folder_name}}'>
                        {{document.report_folder.report_folder_name}} ({{document.report_folder.report_group.report_group_name}})
                    </td>
                    <td class='search-link' data-search='{{document.program.program_name}}'>
                        {{document.program.program_name}}
                    </td>
                    <td class="text-right">
                        {{document.price|currency}}
                    </td>
                    <td class="text-right" data-orderable='false'>
                        <a href='/preview/{{document.document_id}}' class='fb-document action-button btn btn-primary btn-xs' data-toggle='tooltip' data-html='true' title='You are not subscribed<br/>to this report group,<br/>but you can view the<br/>first page for free.' data-viewport='.page-content-holder' data-placement='left'>Preview <span class="fa fa-search fa-lg fa-fw"></span></a>
                        <a class='cart-button removefromcart action-button btn btn-xs btn-danger' data-document='{{document.document_id}}' data-toggle="tooltip" data-placement="top" title="{{document.price|currency}}">
                            <span class="fa fa-minus" aria-hidden="true"></span> Remove from Cart
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="jumbotron text-center text-muted"><h3>Your cart is empty. Add some reports!</h3></div>
    {% endif %}
</div>
<div class="well well-sm text-right">
    {% if data.cart|count > 0 %}
    <button class='clear-cart btn btn-danger pull-left'><span class="fa fa-times" aria-hidden="true"></span> Empty Cart</button>
    {% endif %}
    {% if data.total > 0 %}
    <div class="total-wrapper">
        <strong>Total:</strong> {{data.total|currency}}
    </div>
    <button id='checkout' class="btn btn-lg btn-success"><span class="fa fa-dollar" aria-hidden="true"></span> Checkout</button>
    {% else %}
    <a href="{{url_for('user.documents_list')}}" class="btn btn-info"><span class="fa fa-file fa-fw" aria-hidden="true"></span> View All Reports</a>
    {% endif %}
</div>
<div id="paymentModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body text-center">
                <span class="fa fa-circle-o-notch fa-4x fa-spin small-loader" aria-hidden="true"></span>
                <h2>Processing...</h2>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
function showLoader() {
    $('#paymentModal').modal({
        backdrop: 'static',
        keyboard: false
    });
}

$SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
var groupid = 0;
var handler = StripeCheckout.configure({
    key: '{{data.stripepk}}',
    image: "{{url_for('static', filename='images/stripelogo.png')}}",
    billingAddress: true,
    zipCode: true,
    panelLabel: "Purchase for {{amount}}",
    token: function(token) {
        showLoader();
        $.getJSON($SCRIPT_ROOT + '{{url_for("user.pay_for_reports")}}', {
            token: token.id,
            args: token.args
        }, function(data) {
            if (data.success == 0) {
                location.reload();
            }
            ga('ecommerce:addTransaction', {
                'id': data.stripe_order_id,
                'affiliation': "{{current_user.email}}",
                'revenue': data.total,
            });
            var items = data.items;
            for (i = 0; i < items.length; ++i) {
                ga('ecommerce:addItem', {
                    'id': items[i].id,
                    'name': items[i].name,
                    'sku': items[i].sku,
                    'category': 'Individual Reports',
                    'price': items[i].price,
                    'quantity': '1'
                });
            }
            ga('ecommerce:send');
            window.location.href = '{{url_for("user.library_list")}}';
        });
    }
});

$('#checkout').on('click', function(e) {
    // Open Checkout with further options
    ga('ecommerce:clear');
    handler.open({
        name: "{% if data.cart|count > 1 %}{{data.cart|count}} Reports{% elif data.cart|count == 1 %}{{data.cart[0].document_display_name}}{% endif %}",
        description: 'Permanent report access ({{data.total|currency}})',
        amount: {{data.total * 100}},
        email: '{{current_user.email}}'
    });
    e.preventDefault();
});

// Close Checkout on page navigation
$(window).on('popstate', function() {
    handler.close();
});
</script>
{% endblock %}

app/templates/user/dashboard.html
{% extends "user/_base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        {% if data.new_documents|length == 1 %}
        <p>There has been <strong>{{data.new_documents|length}}</strong> new report uploaded since your last visit.</p>
        {% elif data.new_documents|length > 1 %}
        <p>There have been <strong>{{data.new_documents|length}}</strong> new reports uploaded since your last visit.</p>
        {% endif %}
        {% if data.subscriptions|length == 0 %}
        <p>You are not subscribed to any report groups.</p>
        {% elif data.subscriptions|length == 1 %}
        <p>You are currently subscribed to <strong>{{data.subscriptions|length}}</strong> report group.</p>
        {% else %}
        <p>You are currently subscribed to <strong>{{data.subscriptions|length}}</strong> report groups.</p>
        {% endif %}
        <p class='text-right no-margin'><a href="{{url_for('user.subscriptions_list')}}" class="btn btn-primary btn-large"><span class="fa fa-fw fa-check-square-o" aria-hidden="true"></span> Manage Subscriptions</a></p>
      </div>
    </div>
  </div>
  <div class="row bottom-buffer">
    <div class="col-md-12">
      {% include 'user/publicdocuments.html' %}
    </div>
  </div>
  <div class="row bottom-buffer">
    <div class="col-md-12">
      {% include 'user/documents.html' %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      {% include 'user/library.html' %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/user/subscriptions.html
{% extends "user/_base.html" %}
{% block title %}Subscriptions{% endblock %}
{% block content %}
<div class="page-header">
    <h2>Report Group Subscriptions</h2>
</div>
<div class="page-content no-well">
    <div class="loader"><span class="fa fa-spinner fa-spin fa-5x"></span></div>
    <div class="table-responsive" id="report_groups-wrapper" style="opacity: 0">
        <table class="table table-striped table-responsive table-hover nowrap" id="report_groups-table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th class='sort-by sort-asc'>Group</th>
                    <th class='text-right'>Price</th>
                    <th class='text-right'>Notifications</th>
                    <th class='text-right'>Subscription</th>
                </tr>
            </thead>
            <tbody>
            {% for group in data.groups %}
            {% set subscription = group.get_subscription() %}
                <tr>
                    <td>{{group.report_group_name}}</td>
                    <td class='text-right'>{% if group.price == 0 or not group.price or group.is_free_access() %}Included{% else %}{{group.price|currency}}{% endif %}</td>
                    <td class='text-right'>
                        {% if group.is_notification_enabled() %}
                        <a href='{{url_for("user.disable_notifications_from", group_id=group.report_group_id)}}' data-groupid='{{group.report_group_id}}' class='btn btn-text btn-xs'>Enabled <span class="fa fa-fw fa-envelope" aria-hidden="true"></span></a>
                        {% else %}
                        <a href='{{url_for("user.enable_notifications_from", group_id=group.report_group_id)}}' data-groupid='{{group.report_group_id}}' class='btn btn-text btn-xs{% if not group.is_subscribed() and not group.is_free_access() %} disabled{% endif%}'>Disabled <span class="fa fa-fw fa-envelope-o" aria-hidden="true"></span></a>
                        {% endif %}
                    </td>
                    <td class='text-right'>
                        {% if subscription %}
                            {% if group.price > 0 %}
                                {% if subscription.stripe_autorenew %}
                                <a data-groupid='{{group.report_group_id}}' class='btn btn-text btn-xs' data-placement='left' data-toggle='confirmation' data-title='Cancel and disable auto-renewal?' data-container='body' data-btnOkLabel='Yes' data-btnOkClass='btn btn-sm btn-danger confirm-button' data-btnCancelLabel='No' data-href='javascript:unrenew({{group.report_group_id}})'>Subscribed (will auto-renew {{subscription.current_period_end|datetime}}) <span class="fa fa-fw fa-check-square-o" aria-hidden="true"></span></a>
                                {% else %}
                                <a data-groupid='{{group.report_group_id}}' class='btn btn-text btn-xs' data-placement='left' data-toggle='confirmation' data-title='Enable auto-renewal?' data-container='body' data-btnOkLabel='Yes' data-btnOkClass='btn btn-sm btn-success confirm-button' data-btnCancelLabel='No' data-href='javascript:renew({{group.report_group_id}})'>Subscribed (will NOT auto-renew, expires {{subscription.current_period_end|datetime}}) <span class="fa fa-fw fa-check-square-o" aria-hidden="true"></span></a>
                                {% endif %}
                            {% else %}
                            <a href='{{url_for("user.unsubscribe_to", group_id=group.report_group_id)}}' data-groupid='{{group.report_group_id}}' class='btn btn-text btn-xs'>Enabled <span class="fa fa-fw fa-check-square-o" aria-hidden="true"></span></a>
                            {% endif %}
                        {% elif group.is_free_access() %}
                            <span class="text-success"><span class="fa fa-fw fa-check-square"></span> Free Access</span>
                        {% else %}
                            {% if group.price > 0 and not group.is_free_access() %}
                            <a id="purchase{{group.report_group_id}}" class="btn btn-text btn-xs">Purchase Annual Subscription <span class="fa fa-fw fa-credit-card" aria-hidden="true"></span></a>
                            {% else %}
                            <a href='{{url_for("user.subscribe_to", group_id=group.report_group_id)}}' data-groupid='{{group.report_group_id}}' class='btn btn-text btn-xs'>Disabled <span class="fa fa-fw fa-square-o" aria-hidden="true"></span></a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="text-muted side-buffer top-buffer">
        <p>Subscriptions are valid for one full year of access to all documents within the given report group.</p>
        <p>Contact <a href="mailto:{{config.CONTACT_EMAIL}}">{{config.CONTACT_EMAIL}}</a> for billing questions and assistance.</p>
    </div>
</div>
<div id="paymentModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body text-center">
                <span class="fa fa-circle-o-notch fa-4x fa-spin small-loader" aria-hidden="true"></span>
                <h2>Processing...</h2>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
function showLoader() {
    $('#paymentModal').modal({
        backdrop: 'static',
        keyboard: false
    });
}

function renew(groupid) {
    showLoader();
    $.getJSON($SCRIPT_ROOT + '{{url_for("user.enable_autorenew_ajax")}}', {
        groupid: groupid,
    }, function(data) {
        location.reload();
    });
}

function unrenew(groupid) {
    showLoader();
    $.getJSON($SCRIPT_ROOT + '{{url_for("user.disable_autorenew_ajax")}}', {
        groupid: groupid,
    }, function(data) {
        location.reload();
    });
}

$SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
var groupid = 0;
var handler = StripeCheckout.configure({
    key: '{{data.stripepk}}',
    image: "{{url_for('static', filename='images/stripelogo.png')}}",
    billingAddress: true,
    zipCode: true,
    panelLabel: "Subscribe for {{amount}}",
    token: function(token) {
        showLoader();
        $.getJSON($SCRIPT_ROOT + '{{url_for("user.pay")}}', {
            groupid: groupid,
            token: token.id,
            args: token.args
        }, function(data) {
            ga('ecommerce:addTransaction', {
                'id': data.id,
                'affiliation': "{{current_user.company.company_name}}",
                'revenue': data.price,
            });
            ga('ecommerce:addItem', {
                'id': data.id,
                'name': data.group_name,
                'sku': data.group_id,
                'category': 'Report Groups',
                'price': data.price,
                'quantity': '1'
            });
            ga('ecommerce:send');
            location.reload();
        });
    }
});

{% for group in data.groups %}
{% if group.price > 0 %}
$('#purchase{{group.report_group_id}}').on('click', function(e) {
    // Open Checkout with further options
    groupid = {{group.report_group_id}};
    ga('ecommerce:clear');
    handler.open({
        name: "{{group.report_group_name}}",
        description: '1 year subscription ({{group.price|currency}})',
        amount: {{group.price * 100}},
        email: '{{current_user.email}}'
    });
    e.preventDefault();
});
{% endif %}
{% endfor %}

// Close Checkout on page navigation
$(window).on('popstate', function() {
    handler.close();
});
</script>
{% endblock %}