app/user/views.py
from flask import Blueprint, render_template, request, redirect, url_for,\
                  flash, send_file, session, escape, jsonify, g
from flask.ext import breadcrumbs
from flask_security import login_required, roles_accepted, current_user, utils
from datetime import datetime
from io import BytesIO
from sqlalchemy import desc
from app import app, db, stripe
from app.decorators import crossdomain
from app.models import Company, ReportGroup, ReportFolder, Document, Sponsor,\
                       Program, Role, User, ValidProgram, ReportSubscription,\
                       DocumentPurchase
from app.util.email import send_email


mod_user = Blueprint('user', __name__, url_prefix='/user')


@mod_user.route('/')
@mod_user.route('/dashboard')
@breadcrumbs.register_breadcrumb(mod_user, '.', '<i class="fa fa-fw fa-th-large"></i>')
@login_required
def dashboard():
    documents = current_user.get_recent_user_documents()
    public_documents = current_user.get_recent_public_documents()
    document_library = []
    for purchase in current_user.purchases:
        if len(document_library) <= 5:
            document_library.append(purchase.document)

    data = {
        'documents': documents,
        'public_documents': public_documents,
        'document_library': document_library,
        'subscriptions': current_user.subscriptions
    }

    return render_template('user/dashboard.html', data=data, dashboard=True)


@mod_user.route('/reports')
@breadcrumbs.register_breadcrumb(mod_user, '.reports', 'Reports')
@login_required
def documents_list():
    documents = current_user.get_user_documents()

    data = {
        'documents': documents
    }

    return render_template('user/documents.html', data=data)


@mod_user.route('/publicreports')
@breadcrumbs.register_breadcrumb(mod_user, '.publicreports', 'Public Reports')
@login_required
def public_documents_list():
    public_documents = current_user.get_public_documents()

    data = {
        'public_documents': public_documents
    }

    return render_template('user/publicdocuments.html', data=data)


@mod_user.route('/library')
@breadcrumbs.register_breadcrumb(mod_user, '.library', 'My Library')
@login_required
def library_list():
    document_library = []
    for purchase in current_user.purchases:
        document_library.append(purchase.document)

    data = {
        'document_library': document_library
    }

    return render_template('user/library.html', data=data)


def document_info_user_dlc(*args, **kwargs):
    document_id = request.view_args['document_id']
    document = Document.query.get(document_id)
    return [{'text': document.document_display_name, 'url': url_for('user.document_info', document_id=document_id)}]


@mod_user.route('/reports/info/<int:document_id>', methods=['GET'])
@breadcrumbs.register_breadcrumb(mod_user, '.reports.info', '',
                                 dynamic_list_constructor=document_info_user_dlc)
@login_required
def document_info(document_id):
    document = Document.query.get_or_404(document_id)
    if not document.is_free_access() and not document.get_purchase() and not document.is_subscribed():
        if not document.is_valid():
            flash('You do not have permission to view this resource.', 'error')
            return redirect(url_for('user.dashboard'))

    data = {
        'document': document
    }

    return render_template('user/documentinfo.html', data=data)


@mod_user.route('/cart')
@breadcrumbs.register_breadcrumb(mod_user, '.cart', 'Shopping Cart')
@login_required
def shopping_cart():
    cart = []
    total = 0
    try:
        for item in session['cart']:
            document = Document.query.filter_by(stripe_sku_id=item).first()
            if document:
                cart.append(document)
                total += document.price
    except KeyError:
        cart = []

    data = {
        'cart': cart,
        'total': total,
        'stripepk': app.config['STRIPE_KEYS']['PK']
    }

    return render_template('user/cart.html', data=data, simpletable=True)


# Subscription management

@mod_user.route('/subscriptions')
@breadcrumbs.register_breadcrumb(mod_user, '.subscriptions', 'Subscriptions')
@login_required
@crossdomain(origin='*')
def subscriptions_list():
    groups = ReportGroup.query.all()
    for group in groups:
        group.price = group.get_price()

    data = {
        'groups': groups,
        'subscriptions': current_user.subscriptions,
        'stripepk': app.config['STRIPE_KEYS']['PK']
    }

    return render_template('user/subscriptions.html', data=data, simpletable=True)


@mod_user.route('/subscriptions/subscribe/<int:group_id>')
@login_required
def subscribe_to(group_id):
    report_group = ReportGroup.query.get_or_404(group_id)
    
    if report_group.price > 0 and not report_group.is_free_access():
        flash('You must pay to access this group.', 'error')
        return redirect(url_for('user.subscriptions_list'))

    subscription = ReportSubscription()
    subscription.user_id = current_user.id
    subscription.report_group_id = group_id
    subscription.enable_notifications()

    db.session.add(subscription)
    db.session.commit()
    flash('Subscribed to %s.' % (subscription.report_group.report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/unsubscribe/<int:group_id>')
@login_required
def unsubscribe_to(group_id):
    subscription = ReportSubscription.query.filter_by(user_id=current_user.id).\
                   filter(ReportSubscription.report_group_id == group_id).first_or_404()
    report_group_name = subscription.report_group.report_group_name

    subscription.disable_notifications()

    if subscription.report_group.price > 0 and subscription.stripe_id:
        flash('You cannot unsubscribe to paid groups. Please disable auto-renewal if you wish to cancel.', 'error')
        return redirect(url_for('user.subscriptions_list'))

    db.session.delete(subscription)
    db.session.commit()
    flash('Unsubscribed from %s.' % (report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/notify/<int:group_id>')
@login_required
def enable_notifications_from(group_id):
    report_group = ReportGroup.query.get_or_404(group_id)
    if not report_group.is_subscribed() and not report_group.is_free_access():
        flash('You cannot receive notifications from unsubscribed groups.', 'error')
    else:    
        report_group.enable_notifications()
        db.session.commit()

    flash('Email notifications enabled for %s.' % (report_group.report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/unnotify/<int:group_id>')
@login_required
def disable_notifications_from(group_id):
    report_group = ReportGroup.query.get_or_404(group_id)
    
    report_group.disable_notifications()

    db.session.commit()
    flash('Email notifications disabled for %s.' % (report_group.report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/renew/<int:group_id>')
@login_required
def enable_autorenew(group_id):
    report_subscription = ReportSubscription.query.filter_by(user_id=current_user.id).\
                          filter(ReportSubscription.report_group_id == group_id).first_or_404()
    report_group_name = report_subscription.report_group.report_group_name
    
    # Get the Stripe Customer and reactivate their current subscription
    customer = stripe.Customer.retrieve(current_user.stripe_id)
    subscription = customer.subscriptions.retrieve(report_subscription.stripe_id)
    subscription.plan = report_subscription.report_group_id
    subscription.save()

    report_subscription.stripe_autorenew = 1

    db.session.commit()
    flash('Auto-renewal enabled for %s.' % (report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


@mod_user.route('/subscriptions/unrenew/<int:group_id>')
@login_required
def disable_autorenew(group_id):
    report_subscription = ReportSubscription.query.filter_by(user_id=current_user.id).\
                          filter(ReportSubscription.report_group_id == group_id).first_or_404()
    report_group_name = report_subscription.report_group.report_group_name
    
    # Get the Stripe Customer and delete their subscription at_period_end
    customer = stripe.Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(report_subscription.stripe_id).delete(at_period_end=True)

    report_subscription.stripe_autorenew = 0

    db.session.commit()
    flash('Auto-renewal disabled for %s.' % (report_group_name), 'success')

    return redirect(url_for('user.subscriptions_list'))


## Payments and Subscription Management (AJAX)

@mod_user.route('/_addtocart')
@login_required
def add_to_cart(document_id=None):
    if request.args.get('document_id'):
        document_id = request.args.get('document_id')
    if not document_id:
        return jsonify(result=0)
    document = Document.query.get_or_404(document_id)
    try:
        session['cart'].append(str(document.stripe_sku_id))
    except KeyError:
        session['cart'] = []
        session['cart'].append(str(document.stripe_sku_id))

    return jsonify(result=1, name=document.document_display_name)


@mod_user.route('/_removefromcart')
@login_required
def remove_from_cart(document_id=None):
    if request.args.get('document_id'):
        document_id = request.args.get('document_id')
    if not document_id:
        return jsonify(result=0)
    document = Document.query.get_or_404(document_id)
    try:
        session['cart'].remove(str(document.stripe_sku_id))
    except KeyError:
        return jsonify(result=0)
    return jsonify(result=1, name=document.document_display_name)


@mod_user.route('/_clearcart')
@login_required
def clear_cart():
    try:
        del session['cart']

app/templates/_analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{config.ANALYTICS_TOKEN}}', 'auto');
  ga('require', 'ecommerce');
  ga('send', 'pageview');
</script>

app/templates/_base.html
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="{{config.COMPANY_NAME}}">

    <title>{% if self.title() %}{% block title %}{% endblock %} - {% endif %}{{config.APP_NAME}}</title>

    {% assets "home_css" %}
      <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
    {% endassets %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.png') }}">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" type="text/css">
  </head>

  <body>
    <div id="outdated"></div>
    {% include '_navbar.html' %}
    <div class="page-content-holder">
      {% block content %}
      {% endblock %}
    </div>

    {% include '_footer.html' %}

    {% assets "home_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <script type="text/javscript">
    $(document).ready(function() {
      outdatedBrowser({
        bgColor: '#f25648',
        color: '#ffffff',
        lowerThan: 'transform',
        languagePath: "{{ url_for('static', filename='outdatedbrowser.html') }}"
      })
    });
    </script>
    {% block scripts %}
    {% endblock %}
    {% include '_flash.html' %}
    {% include '_analytics.html' %}
  </body>
</html>

app/templates/_datatables.html
<script type="text/javascript">
$(document).ready(function() {
    $("table[id$='-table']").each(function(index) {
        var sortColumn = $(this).find(".sort-by").index();
        var sortDir = "desc";
        if ($(this).find(".sort-asc").length > 0)
            sortDir = "asc";
        var lengthMenu = [ [15, 50, 100, -1], [15, 50, 100, "All"] ];
        if ($(this).data("table-limit") > 0)
            lengthMenu = [ [$(this).data("table-limit"), 50, 100, -1], [$(this).data("table-limit"), 50, 100, "All"] ];
        var dataType = $(this).attr("id").split("-")[0].replace("_", " ");
        var table = $(this).dataTable({
            "columnDefs": [
                { "className": "control", "orderable": false, "targets": "expand-link" },
                { "targets": "no-sort", "orderable": false }
            ],
            "order": [[ sortColumn, sortDir ]],
            "language": {
                "info": "Showing _START_ to _END_ of _TOTAL_ " + dataType,
                "infoEmpty": "No " + dataType + " available",
                "infoFiltered": "(filtered from _MAX_ " + dataType + ")",
                "lengthMenu": "Display _MENU_ " + dataType,
                "search": "",
                "searchPlaceholder": "Search...",
                "zeroRecords": "No " + dataType + " available",
                "select": {
                    "rows": {
                        "_": "%d " + dataType + " selected",
                        "1": "",
                        "0": "",
                    }
                }
            },
            "responsive": {
                "details": {
                    "type": "column"
                }
            },
            {% if dashboard or simpletable %}
            "paging": false,
            "ordering": false,
            "info": false,
            "filter": false,
            {% else %}
            "select": true,
            "dom": "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>" +
                   "<'row'<'col-sm-12'tr>>" +
                   "<'row'<'col-sm-5'i><'col-sm-7'p>>",
            "buttons": [
                {
                    "extend": "colvis",
                    "columns": ":not(:last-child):not(:first-child)",
                    "text": "<i class='fa fa-fw fa-columns'></i> View"
                },
                {
                    "extend": "copy",
                    "text": "<i class='fa fa-fw fa-clipboard'></i> Copy"
                },
                {
                    "extend": "csv",
                    "text": "<i class='fa fa-fw fa-file-text-o'></i> Save"
                }
            ],
            "lengthMenu": lengthMenu,
            {% endif %}
        });
        $("#" + dataType.replace(" ", "_") + "-wrapper").css("opacity", 1);
    });
    $(".loader").remove();
    $('.dataTables_wrapper').find('.dataTables_filter').append($('<span />', {
        'class': 'fa fa-close search-close close hidden'
    }));
    $('.search-close').click(function() {
        $('.dataTable').DataTable().search('').draw();
        $('input[type=search]').keyup();
        $('.selected').removeClass('selected');
    });
    $('.search-link[data-search=""]').removeClass('search-link');
    {% if dashboard %}
    $('.search-link').removeClass('search-link');
    {% endif %}
    $(document).on('click', '.search-link', function() {
        var query = $(this).data('search');
        $('.dataTable').DataTable().search(query).draw();
        $('input[type=search]').keyup();
    });
    $(document).on('click', '.info-link', function() {
        window.location.href = $(this).data('href');
    });
    $('input[type=search]').keyup(function() {
        if ($(this).val()) {
            $(this).addClass('search-expanded');
            $('.search-close').removeClass('hidden');
        } else {
            $(this).removeClass('search-expanded');
            $('.search-close').addClass('hidden');
        }
    });
    $("tr").click(function() {
      $(this).parent().children().removeClass("selected");
        $(this).addClass("selected");
    });
    $('.nav-pills a').click(function (e) {
        var tables = $('.dataTable').DataTable();
        tables.search('').draw();
        $('input[type=search]').keyup();
        $('.selected').removeClass('selected');
        tables.responsive.recalc();
    });
});
$(document).on('mouseenter', "td", function() {
    var $this = $(this);
    if(this.offsetWidth < this.scrollWidth && !$this.attr('title')) {
        $this.tooltip({
            title: $this.text(),
            placement: "top",
            container: "body"
        });
        $this.tooltip('show');
    }
});
$(document).on('mouseenter', "th", function() {
    var $this = $(this);
    if(this.offsetWidth < this.scrollWidth && !$this.attr('title')) {
        $this.tooltip({
            title: $this.text(),
            placement: "top",
            container: "body"
        });
        $this.tooltip('show');
    }
});
</script>

app/templates/_flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<script>
{% for category, message in messages %}
$.growl({
    title: "<strong>{{ category.title() }}:</strong> ",
    message: "{{ message }}",
},{
    type: "growl-{% if category == 'error' %}danger{% elif category == 'message' %}info{% else %}{{ category }}{% endif %}",
    delay: 7500,
    icon_type: 'class',
    placement: {
        from: "top",
        align: "center"
    },
    animate: {
        enter: 'animated fadeInDown',
        exit: 'animated fadeOutUp'
    },
});
{% endfor %}
</script>
{% endif %}
{% endwith %}

app/templates/_footer.html
<footer class="footer">
  <div class="container{% if 'admin' in request.path or 'user' in request.path %}-fluid{%endif%}">
    <p>{{ config.APP_STYLED_NAME or config.APP_NAME }}</p>
    <p class="copyright">Copyright © {{ get_year() }} <a href='{{config.COMPANY_LINK}}' target='_blank'>{{config.COMPANY_NAME}}.</a> All rights reserved. Powered by <a href='{{config.OWNER_LINK}}' target='_blank'>{{config.OWNER_NAME}}.</a>{% if config.CONTACT_LINK %} Questions? <a href='{{config.CONTACT_LINK}}' target='_blank'>Contact us.</a>{% endif %}</p>
  </div>
</footer>

app/templates/_macros.html
{% macro render_field(field) -%}
  {% set with_label = kwargs.pop('with_label', False) %}
  {% set hidden = kwargs.pop('hidden', False) %}
  {% set group_addon = kwargs.pop('group_addon', None) %}
  {% set group_addon_icon = kwargs.pop('group_addon_icon', None) %}
  {% set group_addon_icon_right = kwargs.pop('group_addon_icon_right', None) %}
  {% set no_group = kwargs.pop('no_group', False) %}
  {% set cols = kwargs.pop('cols', '8') %}
  {% set offset = kwargs.pop('offset', '4') %}
  {% set placeholder = '' %}
  {% if not with_label %}
    {% set placeholder = field.label.text %}
  {% elif field.type == 'QuerySelectMultipleField' %}
    {% set placeholder = 'Select some ' + field.label.text|lower + '...' %}
  {% endif %}
  {% if not no_group %}
  <div class="form-group{% if field.errors %} has-error{% endif %}{% if hidden or field.id == 'csrf_token' %} hidden{% endif %}">
  {% endif %}
    {% if with_label and not field.id == 'submit' %}
      <label for="{{ field.id }}" class="col-sm-4 control-label">
        {{ field.label.text }}
      </label>
      <div class="controls col-sm-{{ cols }}">
    {% else %}
      <div class="controls col-sm-offset-{{ offset }} col-sm-{{ cols }}">
    {% endif %}
    {% if field.type == 'RadioField' %}
      {% set class_ = 'radio '  + kwargs.pop('class_', '') %}
    {% elif field.type == 'MultiCheckboxField' %}
      {% set class_ = 'list-group checked-list-box ' + kwargs.pop('class_', '') %}
    {% else %}
      {% set class_ = 'form-control '  + kwargs.pop('class_', '') %}
    {% endif %}
    {% if field.flags.required %}
      {% set class_ = class_ + 'required' %}
    {% endif %}
    {% if field.type == 'BooleanField' %}
      <div class="checkbox">
        <label>
          {{ field(**kwargs) }}
          {{ field.label.text|safe }}
        </label>
      </div>
    {% else %}
      {% if field.type in ('TextField', 'TextAreaField', 'PasswordField') %}
        {% set class_ = class_ + ' input-xlarge' %}
      {% elif field.type == 'FileField' %}
        {% set class_ = class_ + ' input-file' %}
      {% elif field.type == 'SubmitField' %}
        {% set class_ = 'btn btn-primary btn-lg' %}
      {% endif %}
        {% if group_addon or group_addon_icon or group_addon_icon_right %}
        <div class="input-group">
        {% endif %}
          {% if group_addon or group_addon_icon %}
          <div class="input-group-addon">
          {% if group_addon_icon %}
            <i class="{{ group_addon_icon }}"></i>
          {% else %}
            {{ group_addon|safe }}
          {% endif %}
          </div>
          {% endif %}
          {{ field(class_=class_, placeholder=placeholder, required=field.flags.required, **kwargs) }}
          {% if group_addon_icon_right %}
          <div class="input-group-addon">
            <i class="{{ group_addon_icon_right }}"></i>
          </div>
          {% endif %}
        {% if group_addon or group_addon_icon or group_addon_icon_right %}
        </div>
        {% endif %}
      {% if field.flags.required %}<span class='required_star'>*</span>{% endif %}
    {% endif %}
    {% if field.errors %}
      <span for="{{ field.id }}" class="error help-block">{{ field.errors|join(', ') }}</span>
    {% endif %}
    {% if field.description %}
      <p class="help-block">{{ field.description|safe }}</p>
    {% endif %}
    {% if not field.id == 'submit' %}
      <div class="help-block with-errors no-buffer no-top-buffer"></div>
    {% endif %}
    </div>
  {% if not no_group %}
  </div>
  {% endif %}
{%- endmacro %}

{% macro render_submit(field) -%}
  <div class="form-group{% if field.errors %} error{% endif %}">
    <div class="col-sm-offset-{{ offset }} col-sm-{{ cols }}">
    {{ field(class="btn btn-primary", **kwargs)|safe }}
    </div>
  </div>
{%- endmacro %}

app/templates/_mediaviewer.html
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="{{config.COMPANY_NAME}}">

    <title>{{ document.document_name }}</title>

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/mediaelement/mediaelementplayer.min.css')}}" />
    <script type="text/javascript" src="{{url_for('static', filename='vendor/jquery/js/jquery-2.1.3.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='vendor/mediaelement/mediaelement-and-player.min.js')}}"></script>
  </head>

  <body style="margin: 0 !important; padding: 0 !important; overflow: hidden !important{% if 'video' in document.document_type %}; min-width: 800px; min-height: 600px{% endif %}">
    {% if 'video' in document.document_type %}
    {% if 's3' in document.document_server %}
    <video id="videoPlayer" width="100%" height="100%" controls preload="metadata" autoplay="true">
      <source src="https://s3-{{config['AMAZON_WEB_SERVICES_KEYS']['REGION_NAME']}}.amazonaws.com/{{config['AMAZON_WEB_SERVICES_KEYS']['BUCKET']}}/{{document.document_data}}" type="{{document.document_type}}">
    </video>
    {% else %}
    <video id="videoPlayer" src="/download/{{document.document_id}}" width="100%" height="100%" controls preload="metadata" autoplay="true"></video>
    {% endif %}
    {% elif 'audio' in document.document_type %}
    {% if 's3' in document.document_server %}
    <audio src="https://s3-{{config['AMAZON_WEB_SERVICES_KEYS']['REGION_NAME']}}.amazonaws.com/{{config['AMAZON_WEB_SERVICES_KEYS']['BUCKET']}}/{{document.document_data}}" autoplay="true"></audio>
    {% else %}
    <audio src="/download/{{document.document_id}}" autoplay="true"></audio>
    {% endif %}
    {% endif %}

    <script type="text/javascript">
      $('video,audio').mediaelementplayer({
        audioWidth: '100%',
        audioHeight: '100'
      });
      $(document).ready(function(){
        $('#videoPlayer').bind('contextmenu',function() { return false; });
      });
    </script>
  </body>
</html>

app/templates/_navbar.html
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container{% if 'admin' in request.path or 'user' in request.path or 'help' in request.path %}-fluid{%endif%}">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{url_for('index')}}"><img src="{{ url_for('static', filename='images/logo-nav.gif') }}" alt="{{config.APP_NAME}}" /></a>
    </div>
    <div class="navbar-collapse collapse no-transition">
      <ul class="nav navbar-nav pull-right">
        {% if current_user.is_authenticated %}
          {% if config.DEMO_MODE %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Demo Role <span class="caret"></span></a>
            <ul class="dropdown-menu" style="margin-top: 35px">
              <li><a href="{{url_for('demo_change_role', role_id=1)}}">Super Admin</a></li>
              <li><a href="{{url_for('demo_change_role', role_id=2)}}">Admin</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{{url_for('demo_change_role', role_id=3)}}">Home Office Admin</a></li>
              <li><a href="{{url_for('demo_change_role', role_id=4)}}">Broker/Dealer</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{{url_for('demo_change_role', role_id=5)}}">All-Access Advisor</a></li>
              <li><a href="{{url_for('demo_change_role', role_id=6)}}">Advisor</a></li>
              <li><a href="{{url_for('demo_change_role', role_id=7)}}">User</a></li>
            </ul>
          </li>
          {% endif %}
          <li><a href="{{url_for('account')}}" data-toggle="tooltip" data-placement="left" title="{{ current_user.email }}">Hello, {{ current_user.first_name }}!</a></li>
          {% if current_user.has_role('superadmin') or current_user.has_role('admin') or current_user.has_role('brokeradmin') or current_user.has_role('broker') %}
            <li><a href="{{url_for('admin.dashboard')}}">Dashboard</a></li>
          {% else %}
            <li><a href="{{url_for('user.dashboard')}}">Dashboard</a></li>
            <li><a href="{{url_for('user.shopping_cart')}}">Cart <span class="fa fa-shopping-cart badge"> <span id="cart-count">{{session['cart']|count}}</span></span></a></li>
          {% endif %}
          <li><a href="{{url_for('help_index')}}" target="_blank">Help</a></li>
          <li><a href="{{url_for_security('logout')}}"><span class="fa fa-sign-out" aria-hidden="true"></span> Log Out</a></li>
        {% else %}
          <li><a href="{{config.COMPANY_LINK}}" target="_blank">About Us</a></li>
          <li><a href="{{config.CONTACT_LINK}}" target="_blank">Contact</a></li>
          <li><a href="{{url_for('help_index')}}" target="_blank">Help</a></li>
          <li><a href="{{url_for_security('login')}}"><span class="fa fa-sign-in" aria-hidden="true"></span> Log In</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>

app/templates/_render_errors.html
<script type="text/javascript">
$(document).ready(function() {
  $("form ul li").each(function () {
    $(this).parent().hide();
    $.growl({
      title: "<strong>Error: </strong> ",
      message: $(this).text(),
    },{
      type: "danger",
      delay: 7500,
      icon_type: 'class',
      placement: {
        from: "top",
        align: "center"
      },
      animate: {
        enter: 'animated fadeInDown',
        exit: 'animated fadeOutUp'
      },
    });
  });
});
</script>

app/templates/confirmation.html
{% extends "_base.html" %}
{% block title %}{{title or 'Confirmation'}}{% endblock %}
{% block content %}
<div class="faded-background animated fadeIn vertical-center text-center">
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-4 col-sm-4 pop-box">
        <h2 class="text-{{outcome}}">{{title or outcome.title()}}</h2>
        <p>{{message|safe}}</p>
        <p><script>document.write('<a class="btn btn-text" href="' + document.referrer + '"><i class="fa fa-fw fa-arrow-left"></i> Go Back</a>');</script> or <a class="btn btn-text" href="{{url_for('index')}}">Go Home <i class="fa fa-fw fa-home"></i></a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}